// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.34.0
// source: api/comment/v1/comment.proto

//生成server端： kratos proto server api/comment/v1/comment.proto -t internal/service
//生成client端： kratos proto client api/review/v1/review.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TutorService_GetPostDetailTutor_FullMethodName    = "/api.comment.v1.TutorService/GetPostDetailTutor"
	TutorService_CreatePost_FullMethodName            = "/api.comment.v1.TutorService/CreatePost"
	TutorService_UpdatePost_FullMethodName            = "/api.comment.v1.TutorService/UpdatePost"
	TutorService_DeletePost_FullMethodName            = "/api.comment.v1.TutorService/DeletePost"
	TutorService_ListTutorPosts_FullMethodName        = "/api.comment.v1.TutorService/ListTutorPosts"
	TutorService_ListPostCommentsTutor_FullMethodName = "/api.comment.v1.TutorService/ListPostCommentsTutor"
	TutorService_GetCommentDetailTutor_FullMethodName = "/api.comment.v1.TutorService/GetCommentDetailTutor"
	TutorService_DeleteCommentTutor_FullMethodName    = "/api.comment.v1.TutorService/DeleteCommentTutor"
	TutorService_ReplyComment_FullMethodName          = "/api.comment.v1.TutorService/ReplyComment"
	TutorService_DeleteReply_FullMethodName           = "/api.comment.v1.TutorService/DeleteReply"
)

// TutorServiceClient is the client API for TutorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TutorServiceClient interface {
	GetPostDetailTutor(ctx context.Context, in *GetPostDetailRequest, opts ...grpc.CallOption) (*GetPostDetailReply, error)
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostReply, error)
	UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*UpdatePostReply, error)
	DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostReply, error)
	ListTutorPosts(ctx context.Context, in *ListTutorPostsRequest, opts ...grpc.CallOption) (*ListTutorPostsReply, error)
	ListPostCommentsTutor(ctx context.Context, in *ListPostCommentsRequest, opts ...grpc.CallOption) (*ListPostCommentsReply, error)
	GetCommentDetailTutor(ctx context.Context, in *GetCommentDetailRequest, opts ...grpc.CallOption) (*GetCommentDetailReply, error)
	DeleteCommentTutor(ctx context.Context, in *DeleteCommentTutorRequest, opts ...grpc.CallOption) (*DeleteCommentTutorReply, error)
	ReplyComment(ctx context.Context, in *ReplyCommentRequest, opts ...grpc.CallOption) (*ReplyCommentReply, error)
	DeleteReply(ctx context.Context, in *DeleteReplyRequest, opts ...grpc.CallOption) (*DeleteReplyReply, error)
}

type tutorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTutorServiceClient(cc grpc.ClientConnInterface) TutorServiceClient {
	return &tutorServiceClient{cc}
}

func (c *tutorServiceClient) GetPostDetailTutor(ctx context.Context, in *GetPostDetailRequest, opts ...grpc.CallOption) (*GetPostDetailReply, error) {
	out := new(GetPostDetailReply)
	err := c.cc.Invoke(ctx, TutorService_GetPostDetailTutor_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorServiceClient) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostReply, error) {
	out := new(CreatePostReply)
	err := c.cc.Invoke(ctx, TutorService_CreatePost_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorServiceClient) UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*UpdatePostReply, error) {
	out := new(UpdatePostReply)
	err := c.cc.Invoke(ctx, TutorService_UpdatePost_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorServiceClient) DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostReply, error) {
	out := new(DeletePostReply)
	err := c.cc.Invoke(ctx, TutorService_DeletePost_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorServiceClient) ListTutorPosts(ctx context.Context, in *ListTutorPostsRequest, opts ...grpc.CallOption) (*ListTutorPostsReply, error) {
	out := new(ListTutorPostsReply)
	err := c.cc.Invoke(ctx, TutorService_ListTutorPosts_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorServiceClient) ListPostCommentsTutor(ctx context.Context, in *ListPostCommentsRequest, opts ...grpc.CallOption) (*ListPostCommentsReply, error) {
	out := new(ListPostCommentsReply)
	err := c.cc.Invoke(ctx, TutorService_ListPostCommentsTutor_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorServiceClient) GetCommentDetailTutor(ctx context.Context, in *GetCommentDetailRequest, opts ...grpc.CallOption) (*GetCommentDetailReply, error) {
	out := new(GetCommentDetailReply)
	err := c.cc.Invoke(ctx, TutorService_GetCommentDetailTutor_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorServiceClient) DeleteCommentTutor(ctx context.Context, in *DeleteCommentTutorRequest, opts ...grpc.CallOption) (*DeleteCommentTutorReply, error) {
	out := new(DeleteCommentTutorReply)
	err := c.cc.Invoke(ctx, TutorService_DeleteCommentTutor_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorServiceClient) ReplyComment(ctx context.Context, in *ReplyCommentRequest, opts ...grpc.CallOption) (*ReplyCommentReply, error) {
	out := new(ReplyCommentReply)
	err := c.cc.Invoke(ctx, TutorService_ReplyComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorServiceClient) DeleteReply(ctx context.Context, in *DeleteReplyRequest, opts ...grpc.CallOption) (*DeleteReplyReply, error) {
	out := new(DeleteReplyReply)
	err := c.cc.Invoke(ctx, TutorService_DeleteReply_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TutorServiceServer is the server API for TutorService service.
// All implementations must embed UnimplementedTutorServiceServer
// for forward compatibility
type TutorServiceServer interface {
	GetPostDetailTutor(context.Context, *GetPostDetailRequest) (*GetPostDetailReply, error)
	CreatePost(context.Context, *CreatePostRequest) (*CreatePostReply, error)
	UpdatePost(context.Context, *UpdatePostRequest) (*UpdatePostReply, error)
	DeletePost(context.Context, *DeletePostRequest) (*DeletePostReply, error)
	ListTutorPosts(context.Context, *ListTutorPostsRequest) (*ListTutorPostsReply, error)
	ListPostCommentsTutor(context.Context, *ListPostCommentsRequest) (*ListPostCommentsReply, error)
	GetCommentDetailTutor(context.Context, *GetCommentDetailRequest) (*GetCommentDetailReply, error)
	DeleteCommentTutor(context.Context, *DeleteCommentTutorRequest) (*DeleteCommentTutorReply, error)
	ReplyComment(context.Context, *ReplyCommentRequest) (*ReplyCommentReply, error)
	DeleteReply(context.Context, *DeleteReplyRequest) (*DeleteReplyReply, error)
	mustEmbedUnimplementedTutorServiceServer()
}

// UnimplementedTutorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTutorServiceServer struct {
}

func (UnimplementedTutorServiceServer) GetPostDetailTutor(context.Context, *GetPostDetailRequest) (*GetPostDetailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostDetailTutor not implemented")
}
func (UnimplementedTutorServiceServer) CreatePost(context.Context, *CreatePostRequest) (*CreatePostReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}
func (UnimplementedTutorServiceServer) UpdatePost(context.Context, *UpdatePostRequest) (*UpdatePostReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePost not implemented")
}
func (UnimplementedTutorServiceServer) DeletePost(context.Context, *DeletePostRequest) (*DeletePostReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePost not implemented")
}
func (UnimplementedTutorServiceServer) ListTutorPosts(context.Context, *ListTutorPostsRequest) (*ListTutorPostsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTutorPosts not implemented")
}
func (UnimplementedTutorServiceServer) ListPostCommentsTutor(context.Context, *ListPostCommentsRequest) (*ListPostCommentsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPostCommentsTutor not implemented")
}
func (UnimplementedTutorServiceServer) GetCommentDetailTutor(context.Context, *GetCommentDetailRequest) (*GetCommentDetailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentDetailTutor not implemented")
}
func (UnimplementedTutorServiceServer) DeleteCommentTutor(context.Context, *DeleteCommentTutorRequest) (*DeleteCommentTutorReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCommentTutor not implemented")
}
func (UnimplementedTutorServiceServer) ReplyComment(context.Context, *ReplyCommentRequest) (*ReplyCommentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplyComment not implemented")
}
func (UnimplementedTutorServiceServer) DeleteReply(context.Context, *DeleteReplyRequest) (*DeleteReplyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteReply not implemented")
}
func (UnimplementedTutorServiceServer) mustEmbedUnimplementedTutorServiceServer() {}

// UnsafeTutorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TutorServiceServer will
// result in compilation errors.
type UnsafeTutorServiceServer interface {
	mustEmbedUnimplementedTutorServiceServer()
}

func RegisterTutorServiceServer(s grpc.ServiceRegistrar, srv TutorServiceServer) {
	s.RegisterService(&TutorService_ServiceDesc, srv)
}

func _TutorService_GetPostDetailTutor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).GetPostDetailTutor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_GetPostDetailTutor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).GetPostDetailTutor(ctx, req.(*GetPostDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorService_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_CreatePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).CreatePost(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorService_UpdatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).UpdatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_UpdatePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).UpdatePost(ctx, req.(*UpdatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorService_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_DeletePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).DeletePost(ctx, req.(*DeletePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorService_ListTutorPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTutorPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).ListTutorPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_ListTutorPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).ListTutorPosts(ctx, req.(*ListTutorPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorService_ListPostCommentsTutor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPostCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).ListPostCommentsTutor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_ListPostCommentsTutor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).ListPostCommentsTutor(ctx, req.(*ListPostCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorService_GetCommentDetailTutor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).GetCommentDetailTutor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_GetCommentDetailTutor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).GetCommentDetailTutor(ctx, req.(*GetCommentDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorService_DeleteCommentTutor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentTutorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).DeleteCommentTutor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_DeleteCommentTutor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).DeleteCommentTutor(ctx, req.(*DeleteCommentTutorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorService_ReplyComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplyCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).ReplyComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_ReplyComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).ReplyComment(ctx, req.(*ReplyCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorService_DeleteReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).DeleteReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_DeleteReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).DeleteReply(ctx, req.(*DeleteReplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TutorService_ServiceDesc is the grpc.ServiceDesc for TutorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TutorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.comment.v1.TutorService",
	HandlerType: (*TutorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPostDetailTutor",
			Handler:    _TutorService_GetPostDetailTutor_Handler,
		},
		{
			MethodName: "CreatePost",
			Handler:    _TutorService_CreatePost_Handler,
		},
		{
			MethodName: "UpdatePost",
			Handler:    _TutorService_UpdatePost_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _TutorService_DeletePost_Handler,
		},
		{
			MethodName: "ListTutorPosts",
			Handler:    _TutorService_ListTutorPosts_Handler,
		},
		{
			MethodName: "ListPostCommentsTutor",
			Handler:    _TutorService_ListPostCommentsTutor_Handler,
		},
		{
			MethodName: "GetCommentDetailTutor",
			Handler:    _TutorService_GetCommentDetailTutor_Handler,
		},
		{
			MethodName: "DeleteCommentTutor",
			Handler:    _TutorService_DeleteCommentTutor_Handler,
		},
		{
			MethodName: "ReplyComment",
			Handler:    _TutorService_ReplyComment_Handler,
		},
		{
			MethodName: "DeleteReply",
			Handler:    _TutorService_DeleteReply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/comment/v1/comment.proto",
}

const (
	StudentService_GetPostDetailStudent_FullMethodName    = "/api.comment.v1.StudentService/GetPostDetailStudent"
	StudentService_LikePost_FullMethodName                = "/api.comment.v1.StudentService/LikePost"
	StudentService_UnlikePost_FullMethodName              = "/api.comment.v1.StudentService/UnlikePost"
	StudentService_CreateComment_FullMethodName           = "/api.comment.v1.StudentService/CreateComment"
	StudentService_DeleteMyComment_FullMethodName         = "/api.comment.v1.StudentService/DeleteMyComment"
	StudentService_ListPostCommentsStudent_FullMethodName = "/api.comment.v1.StudentService/ListPostCommentsStudent"
	StudentService_GetCommentDetailStudent_FullMethodName = "/api.comment.v1.StudentService/GetCommentDetailStudent"
	StudentService_ListMyComments_FullMethodName          = "/api.comment.v1.StudentService/ListMyComments"
)

// StudentServiceClient is the client API for StudentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StudentServiceClient interface {
	GetPostDetailStudent(ctx context.Context, in *GetPostDetailRequest, opts ...grpc.CallOption) (*GetPostDetailReply, error)
	LikePost(ctx context.Context, in *LikePostRequest, opts ...grpc.CallOption) (*LikePostReply, error)
	UnlikePost(ctx context.Context, in *UnlikePostRequest, opts ...grpc.CallOption) (*UnlikePostReply, error)
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentReply, error)
	DeleteMyComment(ctx context.Context, in *DeleteMyCommentRequest, opts ...grpc.CallOption) (*DeleteMyCommentReply, error)
	ListPostCommentsStudent(ctx context.Context, in *ListPostCommentsRequest, opts ...grpc.CallOption) (*ListPostCommentsReply, error)
	GetCommentDetailStudent(ctx context.Context, in *GetCommentDetailRequest, opts ...grpc.CallOption) (*GetCommentDetailReply, error)
	ListMyComments(ctx context.Context, in *ListMyCommentsRequest, opts ...grpc.CallOption) (*ListMyCommentsReply, error)
}

type studentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStudentServiceClient(cc grpc.ClientConnInterface) StudentServiceClient {
	return &studentServiceClient{cc}
}

func (c *studentServiceClient) GetPostDetailStudent(ctx context.Context, in *GetPostDetailRequest, opts ...grpc.CallOption) (*GetPostDetailReply, error) {
	out := new(GetPostDetailReply)
	err := c.cc.Invoke(ctx, StudentService_GetPostDetailStudent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentServiceClient) LikePost(ctx context.Context, in *LikePostRequest, opts ...grpc.CallOption) (*LikePostReply, error) {
	out := new(LikePostReply)
	err := c.cc.Invoke(ctx, StudentService_LikePost_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentServiceClient) UnlikePost(ctx context.Context, in *UnlikePostRequest, opts ...grpc.CallOption) (*UnlikePostReply, error) {
	out := new(UnlikePostReply)
	err := c.cc.Invoke(ctx, StudentService_UnlikePost_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentServiceClient) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentReply, error) {
	out := new(CreateCommentReply)
	err := c.cc.Invoke(ctx, StudentService_CreateComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentServiceClient) DeleteMyComment(ctx context.Context, in *DeleteMyCommentRequest, opts ...grpc.CallOption) (*DeleteMyCommentReply, error) {
	out := new(DeleteMyCommentReply)
	err := c.cc.Invoke(ctx, StudentService_DeleteMyComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentServiceClient) ListPostCommentsStudent(ctx context.Context, in *ListPostCommentsRequest, opts ...grpc.CallOption) (*ListPostCommentsReply, error) {
	out := new(ListPostCommentsReply)
	err := c.cc.Invoke(ctx, StudentService_ListPostCommentsStudent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentServiceClient) GetCommentDetailStudent(ctx context.Context, in *GetCommentDetailRequest, opts ...grpc.CallOption) (*GetCommentDetailReply, error) {
	out := new(GetCommentDetailReply)
	err := c.cc.Invoke(ctx, StudentService_GetCommentDetailStudent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentServiceClient) ListMyComments(ctx context.Context, in *ListMyCommentsRequest, opts ...grpc.CallOption) (*ListMyCommentsReply, error) {
	out := new(ListMyCommentsReply)
	err := c.cc.Invoke(ctx, StudentService_ListMyComments_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudentServiceServer is the server API for StudentService service.
// All implementations must embed UnimplementedStudentServiceServer
// for forward compatibility
type StudentServiceServer interface {
	GetPostDetailStudent(context.Context, *GetPostDetailRequest) (*GetPostDetailReply, error)
	LikePost(context.Context, *LikePostRequest) (*LikePostReply, error)
	UnlikePost(context.Context, *UnlikePostRequest) (*UnlikePostReply, error)
	CreateComment(context.Context, *CreateCommentRequest) (*CreateCommentReply, error)
	DeleteMyComment(context.Context, *DeleteMyCommentRequest) (*DeleteMyCommentReply, error)
	ListPostCommentsStudent(context.Context, *ListPostCommentsRequest) (*ListPostCommentsReply, error)
	GetCommentDetailStudent(context.Context, *GetCommentDetailRequest) (*GetCommentDetailReply, error)
	ListMyComments(context.Context, *ListMyCommentsRequest) (*ListMyCommentsReply, error)
	mustEmbedUnimplementedStudentServiceServer()
}

// UnimplementedStudentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStudentServiceServer struct {
}

func (UnimplementedStudentServiceServer) GetPostDetailStudent(context.Context, *GetPostDetailRequest) (*GetPostDetailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostDetailStudent not implemented")
}
func (UnimplementedStudentServiceServer) LikePost(context.Context, *LikePostRequest) (*LikePostReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikePost not implemented")
}
func (UnimplementedStudentServiceServer) UnlikePost(context.Context, *UnlikePostRequest) (*UnlikePostReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlikePost not implemented")
}
func (UnimplementedStudentServiceServer) CreateComment(context.Context, *CreateCommentRequest) (*CreateCommentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedStudentServiceServer) DeleteMyComment(context.Context, *DeleteMyCommentRequest) (*DeleteMyCommentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMyComment not implemented")
}
func (UnimplementedStudentServiceServer) ListPostCommentsStudent(context.Context, *ListPostCommentsRequest) (*ListPostCommentsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPostCommentsStudent not implemented")
}
func (UnimplementedStudentServiceServer) GetCommentDetailStudent(context.Context, *GetCommentDetailRequest) (*GetCommentDetailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentDetailStudent not implemented")
}
func (UnimplementedStudentServiceServer) ListMyComments(context.Context, *ListMyCommentsRequest) (*ListMyCommentsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMyComments not implemented")
}
func (UnimplementedStudentServiceServer) mustEmbedUnimplementedStudentServiceServer() {}

// UnsafeStudentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StudentServiceServer will
// result in compilation errors.
type UnsafeStudentServiceServer interface {
	mustEmbedUnimplementedStudentServiceServer()
}

func RegisterStudentServiceServer(s grpc.ServiceRegistrar, srv StudentServiceServer) {
	s.RegisterService(&StudentService_ServiceDesc, srv)
}

func _StudentService_GetPostDetailStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).GetPostDetailStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentService_GetPostDetailStudent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).GetPostDetailStudent(ctx, req.(*GetPostDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentService_LikePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).LikePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentService_LikePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).LikePost(ctx, req.(*LikePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentService_UnlikePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlikePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).UnlikePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentService_UnlikePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).UnlikePost(ctx, req.(*UnlikePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentService_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentService_CreateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).CreateComment(ctx, req.(*CreateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentService_DeleteMyComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMyCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).DeleteMyComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentService_DeleteMyComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).DeleteMyComment(ctx, req.(*DeleteMyCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentService_ListPostCommentsStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPostCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).ListPostCommentsStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentService_ListPostCommentsStudent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).ListPostCommentsStudent(ctx, req.(*ListPostCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentService_GetCommentDetailStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).GetCommentDetailStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentService_GetCommentDetailStudent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).GetCommentDetailStudent(ctx, req.(*GetCommentDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentService_ListMyComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).ListMyComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentService_ListMyComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).ListMyComments(ctx, req.(*ListMyCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StudentService_ServiceDesc is the grpc.ServiceDesc for StudentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StudentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.comment.v1.StudentService",
	HandlerType: (*StudentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPostDetailStudent",
			Handler:    _StudentService_GetPostDetailStudent_Handler,
		},
		{
			MethodName: "LikePost",
			Handler:    _StudentService_LikePost_Handler,
		},
		{
			MethodName: "UnlikePost",
			Handler:    _StudentService_UnlikePost_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _StudentService_CreateComment_Handler,
		},
		{
			MethodName: "DeleteMyComment",
			Handler:    _StudentService_DeleteMyComment_Handler,
		},
		{
			MethodName: "ListPostCommentsStudent",
			Handler:    _StudentService_ListPostCommentsStudent_Handler,
		},
		{
			MethodName: "GetCommentDetailStudent",
			Handler:    _StudentService_GetCommentDetailStudent_Handler,
		},
		{
			MethodName: "ListMyComments",
			Handler:    _StudentService_ListMyComments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/comment/v1/comment.proto",
}

const (
	OperatorService_GetPostDetailOperator_FullMethodName = "/api.comment.v1.OperatorService/GetPostDetailOperator"
	OperatorService_ListPendingComments_FullMethodName   = "/api.comment.v1.OperatorService/ListPendingComments"
	OperatorService_GetCommentAuditDetail_FullMethodName = "/api.comment.v1.OperatorService/GetCommentAuditDetail"
	OperatorService_AuditComment_FullMethodName          = "/api.comment.v1.OperatorService/AuditComment"
)

// OperatorServiceClient is the client API for OperatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OperatorServiceClient interface {
	GetPostDetailOperator(ctx context.Context, in *GetPostDetailRequest, opts ...grpc.CallOption) (*GetPostDetailReply, error)
	ListPendingComments(ctx context.Context, in *ListPendingCommentsRequest, opts ...grpc.CallOption) (*ListPendingCommentsReply, error)
	GetCommentAuditDetail(ctx context.Context, in *GetCommentAuditDetailRequest, opts ...grpc.CallOption) (*GetCommentAuditDetailReply, error)
	AuditComment(ctx context.Context, in *AuditCommentRequest, opts ...grpc.CallOption) (*AuditCommentReply, error)
}

type operatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOperatorServiceClient(cc grpc.ClientConnInterface) OperatorServiceClient {
	return &operatorServiceClient{cc}
}

func (c *operatorServiceClient) GetPostDetailOperator(ctx context.Context, in *GetPostDetailRequest, opts ...grpc.CallOption) (*GetPostDetailReply, error) {
	out := new(GetPostDetailReply)
	err := c.cc.Invoke(ctx, OperatorService_GetPostDetailOperator_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) ListPendingComments(ctx context.Context, in *ListPendingCommentsRequest, opts ...grpc.CallOption) (*ListPendingCommentsReply, error) {
	out := new(ListPendingCommentsReply)
	err := c.cc.Invoke(ctx, OperatorService_ListPendingComments_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) GetCommentAuditDetail(ctx context.Context, in *GetCommentAuditDetailRequest, opts ...grpc.CallOption) (*GetCommentAuditDetailReply, error) {
	out := new(GetCommentAuditDetailReply)
	err := c.cc.Invoke(ctx, OperatorService_GetCommentAuditDetail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) AuditComment(ctx context.Context, in *AuditCommentRequest, opts ...grpc.CallOption) (*AuditCommentReply, error) {
	out := new(AuditCommentReply)
	err := c.cc.Invoke(ctx, OperatorService_AuditComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperatorServiceServer is the server API for OperatorService service.
// All implementations must embed UnimplementedOperatorServiceServer
// for forward compatibility
type OperatorServiceServer interface {
	GetPostDetailOperator(context.Context, *GetPostDetailRequest) (*GetPostDetailReply, error)
	ListPendingComments(context.Context, *ListPendingCommentsRequest) (*ListPendingCommentsReply, error)
	GetCommentAuditDetail(context.Context, *GetCommentAuditDetailRequest) (*GetCommentAuditDetailReply, error)
	AuditComment(context.Context, *AuditCommentRequest) (*AuditCommentReply, error)
	mustEmbedUnimplementedOperatorServiceServer()
}

// UnimplementedOperatorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOperatorServiceServer struct {
}

func (UnimplementedOperatorServiceServer) GetPostDetailOperator(context.Context, *GetPostDetailRequest) (*GetPostDetailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostDetailOperator not implemented")
}
func (UnimplementedOperatorServiceServer) ListPendingComments(context.Context, *ListPendingCommentsRequest) (*ListPendingCommentsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPendingComments not implemented")
}
func (UnimplementedOperatorServiceServer) GetCommentAuditDetail(context.Context, *GetCommentAuditDetailRequest) (*GetCommentAuditDetailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentAuditDetail not implemented")
}
func (UnimplementedOperatorServiceServer) AuditComment(context.Context, *AuditCommentRequest) (*AuditCommentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuditComment not implemented")
}
func (UnimplementedOperatorServiceServer) mustEmbedUnimplementedOperatorServiceServer() {}

// UnsafeOperatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OperatorServiceServer will
// result in compilation errors.
type UnsafeOperatorServiceServer interface {
	mustEmbedUnimplementedOperatorServiceServer()
}

func RegisterOperatorServiceServer(s grpc.ServiceRegistrar, srv OperatorServiceServer) {
	s.RegisterService(&OperatorService_ServiceDesc, srv)
}

func _OperatorService_GetPostDetailOperator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).GetPostDetailOperator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_GetPostDetailOperator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).GetPostDetailOperator(ctx, req.(*GetPostDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_ListPendingComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPendingCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).ListPendingComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_ListPendingComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).ListPendingComments(ctx, req.(*ListPendingCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_GetCommentAuditDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentAuditDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).GetCommentAuditDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_GetCommentAuditDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).GetCommentAuditDetail(ctx, req.(*GetCommentAuditDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_AuditComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).AuditComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_AuditComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).AuditComment(ctx, req.(*AuditCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OperatorService_ServiceDesc is the grpc.ServiceDesc for OperatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OperatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.comment.v1.OperatorService",
	HandlerType: (*OperatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPostDetailOperator",
			Handler:    _OperatorService_GetPostDetailOperator_Handler,
		},
		{
			MethodName: "ListPendingComments",
			Handler:    _OperatorService_ListPendingComments_Handler,
		},
		{
			MethodName: "GetCommentAuditDetail",
			Handler:    _OperatorService_GetCommentAuditDetail_Handler,
		},
		{
			MethodName: "AuditComment",
			Handler:    _OperatorService_AuditComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/comment/v1/comment.proto",
}

const (
	SearchService_SearchStudentPosts_FullMethodName     = "/api.comment.v1.SearchService/SearchStudentPosts"
	SearchService_SearchStudentComments_FullMethodName  = "/api.comment.v1.SearchService/SearchStudentComments"
	SearchService_SearchTutorPosts_FullMethodName       = "/api.comment.v1.SearchService/SearchTutorPosts"
	SearchService_SearchTutorComments_FullMethodName    = "/api.comment.v1.SearchService/SearchTutorComments"
	SearchService_SearchOperatorComments_FullMethodName = "/api.comment.v1.SearchService/SearchOperatorComments"
)

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchServiceClient interface {
	// 场景 1 & 2: 学生综合搜索知识帖 (支持关键词检索、按助教ID过滤)
	SearchStudentPosts(ctx context.Context, in *SearchStudentPostsRequest, opts ...grpc.CallOption) (*SearchPostsReply, error)
	// 场景 3: 学生搜索评论 (支持全局查"背单词"，或限定在某 post_id 下查)
	SearchStudentComments(ctx context.Context, in *SearchStudentCommentsRequest, opts ...grpc.CallOption) (*SearchCommentsReply, error)
	// 场景 4: 助教搜索自己发布的知识帖 (Token隐式获取 author_id，支持标题/内容关键词)
	SearchTutorPosts(ctx context.Context, in *SearchTutorPostsRequest, opts ...grpc.CallOption) (*SearchPostsReply, error)
	// 场景 5: 助教搜索某知识帖下的学生评论 (查反馈、找问题)
	SearchTutorComments(ctx context.Context, in *SearchTutorCommentsRequest, opts ...grpc.CallOption) (*SearchCommentsReply, error)
	// 场景 6 & 7: 运营全能审核工作台检索 (查待审、查历史审核记录、违规溯源)
	SearchOperatorComments(ctx context.Context, in *SearchOperatorCommentsRequest, opts ...grpc.CallOption) (*SearchCommentsReply, error)
}

type searchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchServiceClient(cc grpc.ClientConnInterface) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) SearchStudentPosts(ctx context.Context, in *SearchStudentPostsRequest, opts ...grpc.CallOption) (*SearchPostsReply, error) {
	out := new(SearchPostsReply)
	err := c.cc.Invoke(ctx, SearchService_SearchStudentPosts_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) SearchStudentComments(ctx context.Context, in *SearchStudentCommentsRequest, opts ...grpc.CallOption) (*SearchCommentsReply, error) {
	out := new(SearchCommentsReply)
	err := c.cc.Invoke(ctx, SearchService_SearchStudentComments_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) SearchTutorPosts(ctx context.Context, in *SearchTutorPostsRequest, opts ...grpc.CallOption) (*SearchPostsReply, error) {
	out := new(SearchPostsReply)
	err := c.cc.Invoke(ctx, SearchService_SearchTutorPosts_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) SearchTutorComments(ctx context.Context, in *SearchTutorCommentsRequest, opts ...grpc.CallOption) (*SearchCommentsReply, error) {
	out := new(SearchCommentsReply)
	err := c.cc.Invoke(ctx, SearchService_SearchTutorComments_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) SearchOperatorComments(ctx context.Context, in *SearchOperatorCommentsRequest, opts ...grpc.CallOption) (*SearchCommentsReply, error) {
	out := new(SearchCommentsReply)
	err := c.cc.Invoke(ctx, SearchService_SearchOperatorComments_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServiceServer is the server API for SearchService service.
// All implementations must embed UnimplementedSearchServiceServer
// for forward compatibility
type SearchServiceServer interface {
	// 场景 1 & 2: 学生综合搜索知识帖 (支持关键词检索、按助教ID过滤)
	SearchStudentPosts(context.Context, *SearchStudentPostsRequest) (*SearchPostsReply, error)
	// 场景 3: 学生搜索评论 (支持全局查"背单词"，或限定在某 post_id 下查)
	SearchStudentComments(context.Context, *SearchStudentCommentsRequest) (*SearchCommentsReply, error)
	// 场景 4: 助教搜索自己发布的知识帖 (Token隐式获取 author_id，支持标题/内容关键词)
	SearchTutorPosts(context.Context, *SearchTutorPostsRequest) (*SearchPostsReply, error)
	// 场景 5: 助教搜索某知识帖下的学生评论 (查反馈、找问题)
	SearchTutorComments(context.Context, *SearchTutorCommentsRequest) (*SearchCommentsReply, error)
	// 场景 6 & 7: 运营全能审核工作台检索 (查待审、查历史审核记录、违规溯源)
	SearchOperatorComments(context.Context, *SearchOperatorCommentsRequest) (*SearchCommentsReply, error)
	mustEmbedUnimplementedSearchServiceServer()
}

// UnimplementedSearchServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSearchServiceServer struct {
}

func (UnimplementedSearchServiceServer) SearchStudentPosts(context.Context, *SearchStudentPostsRequest) (*SearchPostsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchStudentPosts not implemented")
}
func (UnimplementedSearchServiceServer) SearchStudentComments(context.Context, *SearchStudentCommentsRequest) (*SearchCommentsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchStudentComments not implemented")
}
func (UnimplementedSearchServiceServer) SearchTutorPosts(context.Context, *SearchTutorPostsRequest) (*SearchPostsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchTutorPosts not implemented")
}
func (UnimplementedSearchServiceServer) SearchTutorComments(context.Context, *SearchTutorCommentsRequest) (*SearchCommentsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchTutorComments not implemented")
}
func (UnimplementedSearchServiceServer) SearchOperatorComments(context.Context, *SearchOperatorCommentsRequest) (*SearchCommentsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchOperatorComments not implemented")
}
func (UnimplementedSearchServiceServer) mustEmbedUnimplementedSearchServiceServer() {}

// UnsafeSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchServiceServer will
// result in compilation errors.
type UnsafeSearchServiceServer interface {
	mustEmbedUnimplementedSearchServiceServer()
}

func RegisterSearchServiceServer(s grpc.ServiceRegistrar, srv SearchServiceServer) {
	s.RegisterService(&SearchService_ServiceDesc, srv)
}

func _SearchService_SearchStudentPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchStudentPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).SearchStudentPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_SearchStudentPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).SearchStudentPosts(ctx, req.(*SearchStudentPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_SearchStudentComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchStudentCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).SearchStudentComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_SearchStudentComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).SearchStudentComments(ctx, req.(*SearchStudentCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_SearchTutorPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTutorPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).SearchTutorPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_SearchTutorPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).SearchTutorPosts(ctx, req.(*SearchTutorPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_SearchTutorComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTutorCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).SearchTutorComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_SearchTutorComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).SearchTutorComments(ctx, req.(*SearchTutorCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_SearchOperatorComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchOperatorCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).SearchOperatorComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_SearchOperatorComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).SearchOperatorComments(ctx, req.(*SearchOperatorCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchService_ServiceDesc is the grpc.ServiceDesc for SearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.comment.v1.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchStudentPosts",
			Handler:    _SearchService_SearchStudentPosts_Handler,
		},
		{
			MethodName: "SearchStudentComments",
			Handler:    _SearchService_SearchStudentComments_Handler,
		},
		{
			MethodName: "SearchTutorPosts",
			Handler:    _SearchService_SearchTutorPosts_Handler,
		},
		{
			MethodName: "SearchTutorComments",
			Handler:    _SearchService_SearchTutorComments_Handler,
		},
		{
			MethodName: "SearchOperatorComments",
			Handler:    _SearchService_SearchOperatorComments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/comment/v1/comment.proto",
}
