// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"comment-service/internal/biz"
	"comment-service/internal/conf"
	"comment-service/internal/data"
	"comment-service/internal/server"
	"comment-service/internal/service"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, registry *conf.Registry, elasticsearch *conf.Elasticsearch, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	registrar := server.NewRegistrar(registry)
	db, err := data.NewDB(confData)
	if err != nil {
		return nil, nil, err
	}
	client := data.NewRedisClient(confData)
	typedClient, err := data.NewES(elasticsearch)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(db, client, typedClient, logger)
	if err != nil {
		return nil, nil, err
	}
	operatorRepo := data.NewOperatorRepo(dataData, logger)
	operatorUsecase := biz.NewOperatorUsecase(operatorRepo, logger)
	operatorService := service.NewOperatorService(operatorUsecase, logger)
	tutorRepo := data.NewTutorRepo(dataData, logger)
	tutorUsecase := biz.NewTutorUsecase(tutorRepo, logger)
	tutorService := service.NewTutorService(tutorUsecase, logger)
	studentRepo := data.NewStudentRepo(dataData, logger)
	studentUsecase := biz.NewStudentUsecase(studentRepo, logger)
	studentService := service.NewStudentService(studentUsecase, logger)
	searchRepo := data.NewSearchRepo(dataData, logger)
	searchUsecase := biz.NewSearchUsecase(searchRepo, logger)
	searchService := service.NewSearchService(searchUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, operatorService, tutorService, studentService, searchService, logger)
	httpServer := server.NewHTTPServer(confServer, operatorService, tutorService, studentService, searchService, logger)
	app := newApp(logger, registrar, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
