// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"comment-task/internal/biz"
	"comment-task/internal/conf"
	"comment-task/internal/data"
	"comment-task/internal/server"
	"comment-task/internal/service"
	"comment-task/internal/task"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, kafka *conf.Kafka, elasticsearch *conf.Elasticsearch, logger log.Logger) (*kratos.App, func(), error) {
	db, err := data.NewDB(confData)
	if err != nil {
		return nil, nil, err
	}
	client := data.NewRedisClient(confData)
	dataData, cleanup, err := data.NewData(db, client, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo)
	greeterService := service.NewGreeterService(greeterUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	reader := task.NewKafkaReader(kafka)
	postLikeReader := task.NewPostLikeKafkaReader(kafka)
	esClient := task.NewESClient(elasticsearch)
	jobWorker := task.NewJobWorker(reader, postLikeReader, esClient, dataData, logger)
	app := newApp(logger, grpcServer, httpServer, jobWorker)
	return app, func() {
		cleanup()
	}, nil
}
