// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"comment-student/internal/client"
	"comment-student/internal/conf"
	"comment-student/internal/ratelimit"
	"comment-student/internal/server"
	"comment-student/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(confHTTP conf.HTTP, confAuth conf.Auth, confRateLimit conf.RateLimit, confRegistry conf.Registry, confComment conf.CommentService, logger log.Logger) (*kratos.App, func(), error) {
	registry := server.NewConsulRegistry(confRegistry)
	registrar := server.NewRegistrar(registry)
	discovery := server.NewDiscovery(registry)
	commentClient, cleanup, err := client.NewCommentClient(confComment, discovery)
	if err != nil {
		return nil, nil, err
	}
	limiter, cleanup2, err := ratelimit.NewLimiter(confRateLimit, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	studentCommentService := service.NewStudentCommentService(commentClient, logger)
	httpServer := server.NewHTTPServer(confHTTP, confAuth, commentClient, studentCommentService, limiter, logger)
	app := newApp(logger, registrar, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
