// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.0
// source: api/comment/v1/comment.proto

package v1

import (
	context "context"

	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationTutorServiceCreatePost = "/api.comment.v1.TutorService/CreatePost"
const OperationTutorServiceDeleteCommentTutor = "/api.comment.v1.TutorService/DeleteCommentTutor"
const OperationTutorServiceDeletePost = "/api.comment.v1.TutorService/DeletePost"
const OperationTutorServiceDeleteReply = "/api.comment.v1.TutorService/DeleteReply"
const OperationTutorServiceGetCommentDetailTutor = "/api.comment.v1.TutorService/GetCommentDetailTutor"
const OperationTutorServiceGetPostDetailTutor = "/api.comment.v1.TutorService/GetPostDetailTutor"
const OperationTutorServiceListPostCommentsTutor = "/api.comment.v1.TutorService/ListPostCommentsTutor"
const OperationTutorServiceListTutorPosts = "/api.comment.v1.TutorService/ListTutorPosts"
const OperationTutorServiceReplyComment = "/api.comment.v1.TutorService/ReplyComment"
const OperationTutorServiceUpdatePost = "/api.comment.v1.TutorService/UpdatePost"

type TutorServiceHTTPServer interface {
	CreatePost(context.Context, *CreatePostRequest) (*CreatePostReply, error)
	DeleteCommentTutor(context.Context, *DeleteCommentTutorRequest) (*DeleteCommentTutorReply, error)
	DeletePost(context.Context, *DeletePostRequest) (*DeletePostReply, error)
	DeleteReply(context.Context, *DeleteReplyRequest) (*DeleteReplyReply, error)
	GetCommentDetailTutor(context.Context, *GetCommentDetailRequest) (*GetCommentDetailReply, error)
	GetPostDetailTutor(context.Context, *GetPostDetailRequest) (*GetPostDetailReply, error)
	ListPostCommentsTutor(context.Context, *ListPostCommentsRequest) (*ListPostCommentsReply, error)
	ListTutorPosts(context.Context, *ListTutorPostsRequest) (*ListTutorPostsReply, error)
	ReplyComment(context.Context, *ReplyCommentRequest) (*ReplyCommentReply, error)
	UpdatePost(context.Context, *UpdatePostRequest) (*UpdatePostReply, error)
}

func RegisterTutorServiceHTTPServer(s *http.Server, srv TutorServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/tutor/posts/{post_id}", _TutorService_GetPostDetailTutor0_HTTP_Handler(srv))
	r.POST("/v1/tutor/posts", _TutorService_CreatePost0_HTTP_Handler(srv))
	r.PUT("/v1/tutor/posts/{post_id}", _TutorService_UpdatePost0_HTTP_Handler(srv))
	r.DELETE("/v1/tutor/posts/{post_id}", _TutorService_DeletePost0_HTTP_Handler(srv))
	r.GET("/v1/tutor/posts", _TutorService_ListTutorPosts0_HTTP_Handler(srv))
	r.GET("/v1/tutor/posts/{post_id}/comments", _TutorService_ListPostCommentsTutor0_HTTP_Handler(srv))
	r.GET("/v1/tutor/comments/{comment_id}", _TutorService_GetCommentDetailTutor0_HTTP_Handler(srv))
	r.DELETE("/v1/tutor/comments/{comment_id}", _TutorService_DeleteCommentTutor0_HTTP_Handler(srv))
	r.POST("/v1/tutor/comments/{comment_id}/replies", _TutorService_ReplyComment0_HTTP_Handler(srv))
	r.DELETE("/v1/tutor/replies/{comment_reply_id}", _TutorService_DeleteReply0_HTTP_Handler(srv))
}

func _TutorService_GetPostDetailTutor0_HTTP_Handler(srv TutorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPostDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTutorServiceGetPostDetailTutor)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPostDetailTutor(ctx, req.(*GetPostDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetPostDetailReply)
		return ctx.Result(200, reply)
	}
}

func _TutorService_CreatePost0_HTTP_Handler(srv TutorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreatePostRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTutorServiceCreatePost)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreatePost(ctx, req.(*CreatePostRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreatePostReply)
		return ctx.Result(200, reply)
	}
}

func _TutorService_UpdatePost0_HTTP_Handler(srv TutorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdatePostRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTutorServiceUpdatePost)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdatePost(ctx, req.(*UpdatePostRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdatePostReply)
		return ctx.Result(200, reply)
	}
}

func _TutorService_DeletePost0_HTTP_Handler(srv TutorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeletePostRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTutorServiceDeletePost)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeletePost(ctx, req.(*DeletePostRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeletePostReply)
		return ctx.Result(200, reply)
	}
}

func _TutorService_ListTutorPosts0_HTTP_Handler(srv TutorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTutorPostsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTutorServiceListTutorPosts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTutorPosts(ctx, req.(*ListTutorPostsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTutorPostsReply)
		return ctx.Result(200, reply)
	}
}

func _TutorService_ListPostCommentsTutor0_HTTP_Handler(srv TutorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPostCommentsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTutorServiceListPostCommentsTutor)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPostCommentsTutor(ctx, req.(*ListPostCommentsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPostCommentsReply)
		return ctx.Result(200, reply)
	}
}

func _TutorService_GetCommentDetailTutor0_HTTP_Handler(srv TutorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCommentDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTutorServiceGetCommentDetailTutor)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCommentDetailTutor(ctx, req.(*GetCommentDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCommentDetailReply)
		return ctx.Result(200, reply)
	}
}

func _TutorService_DeleteCommentTutor0_HTTP_Handler(srv TutorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteCommentTutorRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTutorServiceDeleteCommentTutor)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteCommentTutor(ctx, req.(*DeleteCommentTutorRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteCommentTutorReply)
		return ctx.Result(200, reply)
	}
}

func _TutorService_ReplyComment0_HTTP_Handler(srv TutorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReplyCommentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTutorServiceReplyComment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ReplyComment(ctx, req.(*ReplyCommentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReplyCommentReply)
		return ctx.Result(200, reply)
	}
}

func _TutorService_DeleteReply0_HTTP_Handler(srv TutorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteReplyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTutorServiceDeleteReply)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteReply(ctx, req.(*DeleteReplyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteReplyReply)
		return ctx.Result(200, reply)
	}
}

type TutorServiceHTTPClient interface {
	CreatePost(ctx context.Context, req *CreatePostRequest, opts ...http.CallOption) (rsp *CreatePostReply, err error)
	DeleteCommentTutor(ctx context.Context, req *DeleteCommentTutorRequest, opts ...http.CallOption) (rsp *DeleteCommentTutorReply, err error)
	DeletePost(ctx context.Context, req *DeletePostRequest, opts ...http.CallOption) (rsp *DeletePostReply, err error)
	DeleteReply(ctx context.Context, req *DeleteReplyRequest, opts ...http.CallOption) (rsp *DeleteReplyReply, err error)
	GetCommentDetailTutor(ctx context.Context, req *GetCommentDetailRequest, opts ...http.CallOption) (rsp *GetCommentDetailReply, err error)
	GetPostDetailTutor(ctx context.Context, req *GetPostDetailRequest, opts ...http.CallOption) (rsp *GetPostDetailReply, err error)
	ListPostCommentsTutor(ctx context.Context, req *ListPostCommentsRequest, opts ...http.CallOption) (rsp *ListPostCommentsReply, err error)
	ListTutorPosts(ctx context.Context, req *ListTutorPostsRequest, opts ...http.CallOption) (rsp *ListTutorPostsReply, err error)
	ReplyComment(ctx context.Context, req *ReplyCommentRequest, opts ...http.CallOption) (rsp *ReplyCommentReply, err error)
	UpdatePost(ctx context.Context, req *UpdatePostRequest, opts ...http.CallOption) (rsp *UpdatePostReply, err error)
}

type TutorServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewTutorServiceHTTPClient(client *http.Client) TutorServiceHTTPClient {
	return &TutorServiceHTTPClientImpl{client}
}

func (c *TutorServiceHTTPClientImpl) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...http.CallOption) (*CreatePostReply, error) {
	var out CreatePostReply
	pattern := "/v1/tutor/posts"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTutorServiceCreatePost))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TutorServiceHTTPClientImpl) DeleteCommentTutor(ctx context.Context, in *DeleteCommentTutorRequest, opts ...http.CallOption) (*DeleteCommentTutorReply, error) {
	var out DeleteCommentTutorReply
	pattern := "/v1/tutor/comments/{comment_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTutorServiceDeleteCommentTutor))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TutorServiceHTTPClientImpl) DeletePost(ctx context.Context, in *DeletePostRequest, opts ...http.CallOption) (*DeletePostReply, error) {
	var out DeletePostReply
	pattern := "/v1/tutor/posts/{post_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTutorServiceDeletePost))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TutorServiceHTTPClientImpl) DeleteReply(ctx context.Context, in *DeleteReplyRequest, opts ...http.CallOption) (*DeleteReplyReply, error) {
	var out DeleteReplyReply
	pattern := "/v1/tutor/replies/{comment_reply_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTutorServiceDeleteReply))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TutorServiceHTTPClientImpl) GetCommentDetailTutor(ctx context.Context, in *GetCommentDetailRequest, opts ...http.CallOption) (*GetCommentDetailReply, error) {
	var out GetCommentDetailReply
	pattern := "/v1/tutor/comments/{comment_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTutorServiceGetCommentDetailTutor))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TutorServiceHTTPClientImpl) GetPostDetailTutor(ctx context.Context, in *GetPostDetailRequest, opts ...http.CallOption) (*GetPostDetailReply, error) {
	var out GetPostDetailReply
	pattern := "/v1/tutor/posts/{post_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTutorServiceGetPostDetailTutor))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TutorServiceHTTPClientImpl) ListPostCommentsTutor(ctx context.Context, in *ListPostCommentsRequest, opts ...http.CallOption) (*ListPostCommentsReply, error) {
	var out ListPostCommentsReply
	pattern := "/v1/tutor/posts/{post_id}/comments"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTutorServiceListPostCommentsTutor))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TutorServiceHTTPClientImpl) ListTutorPosts(ctx context.Context, in *ListTutorPostsRequest, opts ...http.CallOption) (*ListTutorPostsReply, error) {
	var out ListTutorPostsReply
	pattern := "/v1/tutor/posts"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTutorServiceListTutorPosts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TutorServiceHTTPClientImpl) ReplyComment(ctx context.Context, in *ReplyCommentRequest, opts ...http.CallOption) (*ReplyCommentReply, error) {
	var out ReplyCommentReply
	pattern := "/v1/tutor/comments/{comment_id}/replies"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTutorServiceReplyComment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TutorServiceHTTPClientImpl) UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...http.CallOption) (*UpdatePostReply, error) {
	var out UpdatePostReply
	pattern := "/v1/tutor/posts/{post_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTutorServiceUpdatePost))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationStudentServiceCreateComment = "/api.comment.v1.StudentService/CreateComment"
const OperationStudentServiceDeleteMyComment = "/api.comment.v1.StudentService/DeleteMyComment"
const OperationStudentServiceGetCommentDetailStudent = "/api.comment.v1.StudentService/GetCommentDetailStudent"
const OperationStudentServiceGetPostDetailStudent = "/api.comment.v1.StudentService/GetPostDetailStudent"
const OperationStudentServiceLikePost = "/api.comment.v1.StudentService/LikePost"
const OperationStudentServiceListMyComments = "/api.comment.v1.StudentService/ListMyComments"
const OperationStudentServiceListPostCommentsStudent = "/api.comment.v1.StudentService/ListPostCommentsStudent"
const OperationStudentServiceUnlikePost = "/api.comment.v1.StudentService/UnlikePost"

type StudentServiceHTTPServer interface {
	CreateComment(context.Context, *CreateCommentRequest) (*CreateCommentReply, error)
	DeleteMyComment(context.Context, *DeleteMyCommentRequest) (*DeleteMyCommentReply, error)
	GetCommentDetailStudent(context.Context, *GetCommentDetailRequest) (*GetCommentDetailReply, error)
	GetPostDetailStudent(context.Context, *GetPostDetailRequest) (*GetPostDetailReply, error)
	LikePost(context.Context, *LikePostRequest) (*LikePostReply, error)
	ListMyComments(context.Context, *ListMyCommentsRequest) (*ListMyCommentsReply, error)
	ListPostCommentsStudent(context.Context, *ListPostCommentsRequest) (*ListPostCommentsReply, error)
	UnlikePost(context.Context, *UnlikePostRequest) (*UnlikePostReply, error)
}

func RegisterStudentServiceHTTPServer(s *http.Server, srv StudentServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/student/posts/{post_id}", _StudentService_GetPostDetailStudent0_HTTP_Handler(srv))
	r.POST("/v1/student/posts/{post_id}/like", _StudentService_LikePost0_HTTP_Handler(srv))
	r.DELETE("/v1/student/posts/{post_id}/like", _StudentService_UnlikePost0_HTTP_Handler(srv))
	r.POST("/v1/student/posts/{post_id}/comments", _StudentService_CreateComment0_HTTP_Handler(srv))
	r.DELETE("/v1/student/comments/{comment_id}", _StudentService_DeleteMyComment0_HTTP_Handler(srv))
	r.GET("/v1/student/posts/{post_id}/comments", _StudentService_ListPostCommentsStudent0_HTTP_Handler(srv))
	r.GET("/v1/student/comments/{comment_id}", _StudentService_GetCommentDetailStudent0_HTTP_Handler(srv))
	r.GET("/v1/student/comments", _StudentService_ListMyComments0_HTTP_Handler(srv))
}

func _StudentService_GetPostDetailStudent0_HTTP_Handler(srv StudentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPostDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStudentServiceGetPostDetailStudent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPostDetailStudent(ctx, req.(*GetPostDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetPostDetailReply)
		return ctx.Result(200, reply)
	}
}

func _StudentService_LikePost0_HTTP_Handler(srv StudentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LikePostRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStudentServiceLikePost)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LikePost(ctx, req.(*LikePostRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LikePostReply)
		return ctx.Result(200, reply)
	}
}

func _StudentService_UnlikePost0_HTTP_Handler(srv StudentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UnlikePostRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStudentServiceUnlikePost)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UnlikePost(ctx, req.(*UnlikePostRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UnlikePostReply)
		return ctx.Result(200, reply)
	}
}

func _StudentService_CreateComment0_HTTP_Handler(srv StudentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateCommentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStudentServiceCreateComment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateComment(ctx, req.(*CreateCommentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateCommentReply)
		return ctx.Result(200, reply)
	}
}

func _StudentService_DeleteMyComment0_HTTP_Handler(srv StudentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteMyCommentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStudentServiceDeleteMyComment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteMyComment(ctx, req.(*DeleteMyCommentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteMyCommentReply)
		return ctx.Result(200, reply)
	}
}

func _StudentService_ListPostCommentsStudent0_HTTP_Handler(srv StudentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPostCommentsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStudentServiceListPostCommentsStudent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPostCommentsStudent(ctx, req.(*ListPostCommentsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPostCommentsReply)
		return ctx.Result(200, reply)
	}
}

func _StudentService_GetCommentDetailStudent0_HTTP_Handler(srv StudentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCommentDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStudentServiceGetCommentDetailStudent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCommentDetailStudent(ctx, req.(*GetCommentDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCommentDetailReply)
		return ctx.Result(200, reply)
	}
}

func _StudentService_ListMyComments0_HTTP_Handler(srv StudentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMyCommentsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStudentServiceListMyComments)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMyComments(ctx, req.(*ListMyCommentsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListMyCommentsReply)
		return ctx.Result(200, reply)
	}
}

type StudentServiceHTTPClient interface {
	CreateComment(ctx context.Context, req *CreateCommentRequest, opts ...http.CallOption) (rsp *CreateCommentReply, err error)
	DeleteMyComment(ctx context.Context, req *DeleteMyCommentRequest, opts ...http.CallOption) (rsp *DeleteMyCommentReply, err error)
	GetCommentDetailStudent(ctx context.Context, req *GetCommentDetailRequest, opts ...http.CallOption) (rsp *GetCommentDetailReply, err error)
	GetPostDetailStudent(ctx context.Context, req *GetPostDetailRequest, opts ...http.CallOption) (rsp *GetPostDetailReply, err error)
	LikePost(ctx context.Context, req *LikePostRequest, opts ...http.CallOption) (rsp *LikePostReply, err error)
	ListMyComments(ctx context.Context, req *ListMyCommentsRequest, opts ...http.CallOption) (rsp *ListMyCommentsReply, err error)
	ListPostCommentsStudent(ctx context.Context, req *ListPostCommentsRequest, opts ...http.CallOption) (rsp *ListPostCommentsReply, err error)
	UnlikePost(ctx context.Context, req *UnlikePostRequest, opts ...http.CallOption) (rsp *UnlikePostReply, err error)
}

type StudentServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewStudentServiceHTTPClient(client *http.Client) StudentServiceHTTPClient {
	return &StudentServiceHTTPClientImpl{client}
}

func (c *StudentServiceHTTPClientImpl) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...http.CallOption) (*CreateCommentReply, error) {
	var out CreateCommentReply
	pattern := "/v1/student/posts/{post_id}/comments"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStudentServiceCreateComment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StudentServiceHTTPClientImpl) DeleteMyComment(ctx context.Context, in *DeleteMyCommentRequest, opts ...http.CallOption) (*DeleteMyCommentReply, error) {
	var out DeleteMyCommentReply
	pattern := "/v1/student/comments/{comment_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStudentServiceDeleteMyComment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StudentServiceHTTPClientImpl) GetCommentDetailStudent(ctx context.Context, in *GetCommentDetailRequest, opts ...http.CallOption) (*GetCommentDetailReply, error) {
	var out GetCommentDetailReply
	pattern := "/v1/student/comments/{comment_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStudentServiceGetCommentDetailStudent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StudentServiceHTTPClientImpl) GetPostDetailStudent(ctx context.Context, in *GetPostDetailRequest, opts ...http.CallOption) (*GetPostDetailReply, error) {
	var out GetPostDetailReply
	pattern := "/v1/student/posts/{post_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStudentServiceGetPostDetailStudent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StudentServiceHTTPClientImpl) LikePost(ctx context.Context, in *LikePostRequest, opts ...http.CallOption) (*LikePostReply, error) {
	var out LikePostReply
	pattern := "/v1/student/posts/{post_id}/like"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStudentServiceLikePost))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StudentServiceHTTPClientImpl) ListMyComments(ctx context.Context, in *ListMyCommentsRequest, opts ...http.CallOption) (*ListMyCommentsReply, error) {
	var out ListMyCommentsReply
	pattern := "/v1/student/comments"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStudentServiceListMyComments))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StudentServiceHTTPClientImpl) ListPostCommentsStudent(ctx context.Context, in *ListPostCommentsRequest, opts ...http.CallOption) (*ListPostCommentsReply, error) {
	var out ListPostCommentsReply
	pattern := "/v1/student/posts/{post_id}/comments"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStudentServiceListPostCommentsStudent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StudentServiceHTTPClientImpl) UnlikePost(ctx context.Context, in *UnlikePostRequest, opts ...http.CallOption) (*UnlikePostReply, error) {
	var out UnlikePostReply
	pattern := "/v1/student/posts/{post_id}/like"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStudentServiceUnlikePost))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationOperatorServiceAuditComment = "/api.comment.v1.OperatorService/AuditComment"
const OperationOperatorServiceGetCommentAuditDetail = "/api.comment.v1.OperatorService/GetCommentAuditDetail"
const OperationOperatorServiceGetPostDetailOperator = "/api.comment.v1.OperatorService/GetPostDetailOperator"
const OperationOperatorServiceListPendingComments = "/api.comment.v1.OperatorService/ListPendingComments"

type OperatorServiceHTTPServer interface {
	AuditComment(context.Context, *AuditCommentRequest) (*AuditCommentReply, error)
	GetCommentAuditDetail(context.Context, *GetCommentAuditDetailRequest) (*GetCommentAuditDetailReply, error)
	GetPostDetailOperator(context.Context, *GetPostDetailRequest) (*GetPostDetailReply, error)
	ListPendingComments(context.Context, *ListPendingCommentsRequest) (*ListPendingCommentsReply, error)
}

func RegisterOperatorServiceHTTPServer(s *http.Server, srv OperatorServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/operator/posts/{post_id}", _OperatorService_GetPostDetailOperator0_HTTP_Handler(srv))
	r.GET("/v1/operator/comments/pending", _OperatorService_ListPendingComments0_HTTP_Handler(srv))
	r.GET("/v1/operator/comments/{comment_id}/audit", _OperatorService_GetCommentAuditDetail0_HTTP_Handler(srv))
	r.POST("/v1/operator/comments/{comment_id}/audit", _OperatorService_AuditComment0_HTTP_Handler(srv))
}

func _OperatorService_GetPostDetailOperator0_HTTP_Handler(srv OperatorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPostDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOperatorServiceGetPostDetailOperator)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPostDetailOperator(ctx, req.(*GetPostDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetPostDetailReply)
		return ctx.Result(200, reply)
	}
}

func _OperatorService_ListPendingComments0_HTTP_Handler(srv OperatorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPendingCommentsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOperatorServiceListPendingComments)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPendingComments(ctx, req.(*ListPendingCommentsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPendingCommentsReply)
		return ctx.Result(200, reply)
	}
}

func _OperatorService_GetCommentAuditDetail0_HTTP_Handler(srv OperatorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCommentAuditDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOperatorServiceGetCommentAuditDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCommentAuditDetail(ctx, req.(*GetCommentAuditDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCommentAuditDetailReply)
		return ctx.Result(200, reply)
	}
}

func _OperatorService_AuditComment0_HTTP_Handler(srv OperatorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AuditCommentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOperatorServiceAuditComment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AuditComment(ctx, req.(*AuditCommentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AuditCommentReply)
		return ctx.Result(200, reply)
	}
}

type OperatorServiceHTTPClient interface {
	AuditComment(ctx context.Context, req *AuditCommentRequest, opts ...http.CallOption) (rsp *AuditCommentReply, err error)
	GetCommentAuditDetail(ctx context.Context, req *GetCommentAuditDetailRequest, opts ...http.CallOption) (rsp *GetCommentAuditDetailReply, err error)
	GetPostDetailOperator(ctx context.Context, req *GetPostDetailRequest, opts ...http.CallOption) (rsp *GetPostDetailReply, err error)
	ListPendingComments(ctx context.Context, req *ListPendingCommentsRequest, opts ...http.CallOption) (rsp *ListPendingCommentsReply, err error)
}

type OperatorServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewOperatorServiceHTTPClient(client *http.Client) OperatorServiceHTTPClient {
	return &OperatorServiceHTTPClientImpl{client}
}

func (c *OperatorServiceHTTPClientImpl) AuditComment(ctx context.Context, in *AuditCommentRequest, opts ...http.CallOption) (*AuditCommentReply, error) {
	var out AuditCommentReply
	pattern := "/v1/operator/comments/{comment_id}/audit"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOperatorServiceAuditComment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OperatorServiceHTTPClientImpl) GetCommentAuditDetail(ctx context.Context, in *GetCommentAuditDetailRequest, opts ...http.CallOption) (*GetCommentAuditDetailReply, error) {
	var out GetCommentAuditDetailReply
	pattern := "/v1/operator/comments/{comment_id}/audit"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOperatorServiceGetCommentAuditDetail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OperatorServiceHTTPClientImpl) GetPostDetailOperator(ctx context.Context, in *GetPostDetailRequest, opts ...http.CallOption) (*GetPostDetailReply, error) {
	var out GetPostDetailReply
	pattern := "/v1/operator/posts/{post_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOperatorServiceGetPostDetailOperator))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OperatorServiceHTTPClientImpl) ListPendingComments(ctx context.Context, in *ListPendingCommentsRequest, opts ...http.CallOption) (*ListPendingCommentsReply, error) {
	var out ListPendingCommentsReply
	pattern := "/v1/operator/comments/pending"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOperatorServiceListPendingComments))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationSearchServiceSearchOperatorComments = "/api.comment.v1.SearchService/SearchOperatorComments"
const OperationSearchServiceSearchStudentComments = "/api.comment.v1.SearchService/SearchStudentComments"
const OperationSearchServiceSearchStudentPosts = "/api.comment.v1.SearchService/SearchStudentPosts"
const OperationSearchServiceSearchTutorComments = "/api.comment.v1.SearchService/SearchTutorComments"
const OperationSearchServiceSearchTutorPosts = "/api.comment.v1.SearchService/SearchTutorPosts"

type SearchServiceHTTPServer interface {
	// SearchOperatorComments 场景 6 & 7: 运营全能审核工作台检索 (查待审、查历史审核记录、违规溯源)
	SearchOperatorComments(context.Context, *SearchOperatorCommentsRequest) (*SearchCommentsReply, error)
	// SearchStudentComments 场景 3: 学生搜索评论 (支持全局查"背单词"，或限定在某 post_id 下查)
	SearchStudentComments(context.Context, *SearchStudentCommentsRequest) (*SearchCommentsReply, error)
	// SearchStudentPosts 场景 1 & 2: 学生综合搜索知识帖 (支持关键词检索、按助教ID过滤)
	SearchStudentPosts(context.Context, *SearchStudentPostsRequest) (*SearchPostsReply, error)
	// SearchTutorComments 场景 5: 助教搜索某知识帖下的学生评论 (查反馈、找问题)
	SearchTutorComments(context.Context, *SearchTutorCommentsRequest) (*SearchCommentsReply, error)
	// SearchTutorPosts 场景 4: 助教搜索自己发布的知识帖 (Token隐式获取 author_id，支持标题/内容关键词)
	SearchTutorPosts(context.Context, *SearchTutorPostsRequest) (*SearchPostsReply, error)
}

func RegisterSearchServiceHTTPServer(s *http.Server, srv SearchServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/student/search/posts", _SearchService_SearchStudentPosts0_HTTP_Handler(srv))
	r.GET("/v1/student/search/comments", _SearchService_SearchStudentComments0_HTTP_Handler(srv))
	r.GET("/v1/tutor/search/posts", _SearchService_SearchTutorPosts0_HTTP_Handler(srv))
	r.GET("/v1/tutor/posts/{post_id}/comments/search", _SearchService_SearchTutorComments0_HTTP_Handler(srv))
	r.GET("/v1/operator/search/comments", _SearchService_SearchOperatorComments0_HTTP_Handler(srv))
}

func _SearchService_SearchStudentPosts0_HTTP_Handler(srv SearchServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SearchStudentPostsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSearchServiceSearchStudentPosts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SearchStudentPosts(ctx, req.(*SearchStudentPostsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SearchPostsReply)
		return ctx.Result(200, reply)
	}
}

func _SearchService_SearchStudentComments0_HTTP_Handler(srv SearchServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SearchStudentCommentsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSearchServiceSearchStudentComments)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SearchStudentComments(ctx, req.(*SearchStudentCommentsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SearchCommentsReply)
		return ctx.Result(200, reply)
	}
}

func _SearchService_SearchTutorPosts0_HTTP_Handler(srv SearchServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SearchTutorPostsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSearchServiceSearchTutorPosts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SearchTutorPosts(ctx, req.(*SearchTutorPostsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SearchPostsReply)
		return ctx.Result(200, reply)
	}
}

func _SearchService_SearchTutorComments0_HTTP_Handler(srv SearchServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SearchTutorCommentsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSearchServiceSearchTutorComments)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SearchTutorComments(ctx, req.(*SearchTutorCommentsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SearchCommentsReply)
		return ctx.Result(200, reply)
	}
}

func _SearchService_SearchOperatorComments0_HTTP_Handler(srv SearchServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SearchOperatorCommentsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSearchServiceSearchOperatorComments)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SearchOperatorComments(ctx, req.(*SearchOperatorCommentsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SearchCommentsReply)
		return ctx.Result(200, reply)
	}
}

type SearchServiceHTTPClient interface {
	// SearchOperatorComments 场景 6 & 7: 运营全能审核工作台检索 (查待审、查历史审核记录、违规溯源)
	SearchOperatorComments(ctx context.Context, req *SearchOperatorCommentsRequest, opts ...http.CallOption) (rsp *SearchCommentsReply, err error)
	// SearchStudentComments 场景 3: 学生搜索评论 (支持全局查"背单词"，或限定在某 post_id 下查)
	SearchStudentComments(ctx context.Context, req *SearchStudentCommentsRequest, opts ...http.CallOption) (rsp *SearchCommentsReply, err error)
	// SearchStudentPosts 场景 1 & 2: 学生综合搜索知识帖 (支持关键词检索、按助教ID过滤)
	SearchStudentPosts(ctx context.Context, req *SearchStudentPostsRequest, opts ...http.CallOption) (rsp *SearchPostsReply, err error)
	// SearchTutorComments 场景 5: 助教搜索某知识帖下的学生评论 (查反馈、找问题)
	SearchTutorComments(ctx context.Context, req *SearchTutorCommentsRequest, opts ...http.CallOption) (rsp *SearchCommentsReply, err error)
	// SearchTutorPosts 场景 4: 助教搜索自己发布的知识帖 (Token隐式获取 author_id，支持标题/内容关键词)
	SearchTutorPosts(ctx context.Context, req *SearchTutorPostsRequest, opts ...http.CallOption) (rsp *SearchPostsReply, err error)
}

type SearchServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSearchServiceHTTPClient(client *http.Client) SearchServiceHTTPClient {
	return &SearchServiceHTTPClientImpl{client}
}

// SearchOperatorComments 场景 6 & 7: 运营全能审核工作台检索 (查待审、查历史审核记录、违规溯源)
func (c *SearchServiceHTTPClientImpl) SearchOperatorComments(ctx context.Context, in *SearchOperatorCommentsRequest, opts ...http.CallOption) (*SearchCommentsReply, error) {
	var out SearchCommentsReply
	pattern := "/v1/operator/search/comments"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSearchServiceSearchOperatorComments))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SearchStudentComments 场景 3: 学生搜索评论 (支持全局查"背单词"，或限定在某 post_id 下查)
func (c *SearchServiceHTTPClientImpl) SearchStudentComments(ctx context.Context, in *SearchStudentCommentsRequest, opts ...http.CallOption) (*SearchCommentsReply, error) {
	var out SearchCommentsReply
	pattern := "/v1/student/search/comments"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSearchServiceSearchStudentComments))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SearchStudentPosts 场景 1 & 2: 学生综合搜索知识帖 (支持关键词检索、按助教ID过滤)
func (c *SearchServiceHTTPClientImpl) SearchStudentPosts(ctx context.Context, in *SearchStudentPostsRequest, opts ...http.CallOption) (*SearchPostsReply, error) {
	var out SearchPostsReply
	pattern := "/v1/student/search/posts"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSearchServiceSearchStudentPosts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SearchTutorComments 场景 5: 助教搜索某知识帖下的学生评论 (查反馈、找问题)
func (c *SearchServiceHTTPClientImpl) SearchTutorComments(ctx context.Context, in *SearchTutorCommentsRequest, opts ...http.CallOption) (*SearchCommentsReply, error) {
	var out SearchCommentsReply
	pattern := "/v1/tutor/posts/{post_id}/comments/search"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSearchServiceSearchTutorComments))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SearchTutorPosts 场景 4: 助教搜索自己发布的知识帖 (Token隐式获取 author_id，支持标题/内容关键词)
func (c *SearchServiceHTTPClientImpl) SearchTutorPosts(ctx context.Context, in *SearchTutorPostsRequest, opts ...http.CallOption) (*SearchPostsReply, error) {
	var out SearchPostsReply
	pattern := "/v1/tutor/search/posts"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSearchServiceSearchTutorPosts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
