// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePostLike = "post_like"

// PostLike 知识帖点赞表
type PostLike struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PostID    int64     `gorm:"column:post_id;not null" json:"post_id"`
	StudentID int64     `gorm:"column:student_id;not null;comment:学生ID" json:"student_id"`        // 学生ID
	Status    int32     `gorm:"column:status;not null;default:1;comment:1已点赞 0已取消" json:"status"` // 1已点赞 0已取消
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName PostLike's table name
func (*PostLike) TableName() string {
	return TableNamePostLike
}
