// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePost = "post"

// Post 知识帖表
type Post struct {
	ID           int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PostID       int64          `gorm:"column:post_id;not null;comment:知识帖ID" json:"post_id"`    // 知识帖ID
	AuthorID     int64          `gorm:"column:author_id;not null;comment:助教ID" json:"author_id"` // 助教ID
	Title        string         `gorm:"column:title;not null" json:"title"`
	Content      string         `gorm:"column:content;not null" json:"content"`
	Status       int32          `gorm:"column:status;not null;default:1;comment:1已发布 2已下架/删除" json:"status"` // 1已发布 2已下架/删除
	LikeCount    int32          `gorm:"-" json:"like_count"`
	CommentCount int32          `gorm:"-" json:"comment_count"`
	CreatedAt    time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Post's table name
func (*Post) TableName() string {
	return TableNamePost
}
