// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameStudyComment = "study_comment"

// StudyComment 学生学习打卡评论表
type StudyComment struct {
	ID                 int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CommentID          int64          `gorm:"column:comment_id;not null;comment:学生评论ID" json:"comment_id"`                     // 学生评论ID
	PostID             int64          `gorm:"column:post_id;not null;comment:知识帖ID" json:"post_id"`                            // 知识帖ID
	StudentID          int64          `gorm:"column:student_id;not null;comment:评论学生ID" json:"student_id"`                     // 评论学生ID
	Content            string         `gorm:"column:content;not null;comment:评论内容" json:"content"`                             // 评论内容
	VisibleStatus      int32          `gorm:"column:visible_status;not null;default:1;comment:1可见 2不可见" json:"visible_status"` // 1可见 2不可见
	AuditStatus        int32          `gorm:"column:audit_status;not null;comment:0待审核 1审核通过 2审核驳回" json:"audit_status"`       // 0待审核 1审核通过 2审核驳回
	ManualReviewReason *string        `gorm:"column:manual_review_reason;comment:人工驳回原因" json:"manual_review_reason"`          // 人工驳回原因
	ManualOperatorID   int64          `gorm:"column:manual_operator_id;not null;comment:运营ID" json:"manual_operator_id"`       // 运营ID
	ReplyID            int64          `gorm:"column:reply_id;not null;comment:助教回复ID" json:"reply_id"`
	ReplyTutorID       int64          `gorm:"column:reply_tutor_id;not null;comment:回复助教ID" json:"reply_tutor_id"`
	ReplyContent       *string        `gorm:"column:reply_content;comment:助教一次性指导回复" json:"reply_content"`
	ReplyStatus        int32          `gorm:"column:reply_status;not null;comment:0未回复 1已回复 2已撤回" json:"reply_status"`
	RepliedAt          *time.Time     `gorm:"column:replied_at;comment:回复时间" json:"replied_at"`
	DeletedAt          gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"` // 删除时间
	CreatedAt          time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt          time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName StudyComment's table name
func (*StudyComment) TableName() string {
	return TableNameStudyComment
}
