// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameStudyCommentReply = "study_comment_reply"

// StudyCommentReply 助教评论回复表
type StudyCommentReply struct {
	ID             int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CommentReplyID int64          `gorm:"column:comment_reply_id;not null;comment:评论回复ID" json:"comment_reply_id"` // 评论回复ID
	CommentID      int64          `gorm:"column:comment_id;not null;comment:所属评论ID" json:"comment_id"`             // 所属评论ID
	TutorID        int64          `gorm:"column:tutor_id;not null;comment:助教ID" json:"tutor_id"`                   // 助教ID
	PostID         int64          `gorm:"column:post_id;not null;comment:知识帖ID" json:"post_id"`                    // 知识帖ID
	Content        string         `gorm:"column:content;not null;comment:回复内容" json:"content"`                     // 回复内容
	Status         int32          `gorm:"column:status;not null;default:1;comment:1正常 2已删除" json:"status"`         // 1正常 2已删除
	DeletedBy      int64          `gorm:"column:deleted_by;not null;comment:删除操作人ID" json:"deleted_by"`            // 删除操作人ID
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                        // 删除时间
	CreatedAt      time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName StudyCommentReply's table name
func (*StudyCommentReply) TableName() string {
	return TableNameStudyCommentReply
}
