// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"comment-service/dal/model"
)

func newStudyCommentReply(db *gorm.DB, opts ...gen.DOOption) studyCommentReply {
	_studyCommentReply := studyCommentReply{}

	_studyCommentReply.studyCommentReplyDo.UseDB(db, opts...)
	_studyCommentReply.studyCommentReplyDo.UseModel(&model.StudyCommentReply{})

	tableName := _studyCommentReply.studyCommentReplyDo.TableName()
	_studyCommentReply.ALL = field.NewAsterisk(tableName)
	_studyCommentReply.ID = field.NewInt64(tableName, "id")
	_studyCommentReply.CommentReplyID = field.NewInt64(tableName, "comment_reply_id")
	_studyCommentReply.CommentID = field.NewInt64(tableName, "comment_id")
	_studyCommentReply.TutorID = field.NewInt64(tableName, "tutor_id")
	_studyCommentReply.PostID = field.NewInt64(tableName, "post_id")
	_studyCommentReply.Content = field.NewString(tableName, "content")
	_studyCommentReply.Status = field.NewInt32(tableName, "status")
	_studyCommentReply.DeletedBy = field.NewInt64(tableName, "deleted_by")
	_studyCommentReply.DeletedAt = field.NewField(tableName, "deleted_at")
	_studyCommentReply.CreatedAt = field.NewTime(tableName, "created_at")
	_studyCommentReply.UpdatedAt = field.NewTime(tableName, "updated_at")

	_studyCommentReply.fillFieldMap()

	return _studyCommentReply
}

// studyCommentReply 助教评论回复表
type studyCommentReply struct {
	studyCommentReplyDo studyCommentReplyDo

	ALL            field.Asterisk
	ID             field.Int64
	CommentReplyID field.Int64  // 评论回复ID
	CommentID      field.Int64  // 所属评论ID
	TutorID        field.Int64  // 助教ID
	PostID         field.Int64  // 知识帖ID
	Content        field.String // 回复内容
	Status         field.Int32  // 1正常 2已删除
	DeletedBy      field.Int64  // 删除操作人ID
	DeletedAt      field.Field  // 删除时间
	CreatedAt      field.Time
	UpdatedAt      field.Time

	fieldMap map[string]field.Expr
}

func (s studyCommentReply) Table(newTableName string) *studyCommentReply {
	s.studyCommentReplyDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s studyCommentReply) As(alias string) *studyCommentReply {
	s.studyCommentReplyDo.DO = *(s.studyCommentReplyDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *studyCommentReply) updateTableName(table string) *studyCommentReply {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.CommentReplyID = field.NewInt64(table, "comment_reply_id")
	s.CommentID = field.NewInt64(table, "comment_id")
	s.TutorID = field.NewInt64(table, "tutor_id")
	s.PostID = field.NewInt64(table, "post_id")
	s.Content = field.NewString(table, "content")
	s.Status = field.NewInt32(table, "status")
	s.DeletedBy = field.NewInt64(table, "deleted_by")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *studyCommentReply) WithContext(ctx context.Context) IStudyCommentReplyDo {
	return s.studyCommentReplyDo.WithContext(ctx)
}

func (s studyCommentReply) TableName() string { return s.studyCommentReplyDo.TableName() }

func (s studyCommentReply) Alias() string { return s.studyCommentReplyDo.Alias() }

func (s studyCommentReply) Columns(cols ...field.Expr) gen.Columns {
	return s.studyCommentReplyDo.Columns(cols...)
}

func (s *studyCommentReply) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *studyCommentReply) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 11)
	s.fieldMap["id"] = s.ID
	s.fieldMap["comment_reply_id"] = s.CommentReplyID
	s.fieldMap["comment_id"] = s.CommentID
	s.fieldMap["tutor_id"] = s.TutorID
	s.fieldMap["post_id"] = s.PostID
	s.fieldMap["content"] = s.Content
	s.fieldMap["status"] = s.Status
	s.fieldMap["deleted_by"] = s.DeletedBy
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s studyCommentReply) clone(db *gorm.DB) studyCommentReply {
	s.studyCommentReplyDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s studyCommentReply) replaceDB(db *gorm.DB) studyCommentReply {
	s.studyCommentReplyDo.ReplaceDB(db)
	return s
}

type studyCommentReplyDo struct{ gen.DO }

type IStudyCommentReplyDo interface {
	gen.SubQuery
	Debug() IStudyCommentReplyDo
	WithContext(ctx context.Context) IStudyCommentReplyDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IStudyCommentReplyDo
	WriteDB() IStudyCommentReplyDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IStudyCommentReplyDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IStudyCommentReplyDo
	Not(conds ...gen.Condition) IStudyCommentReplyDo
	Or(conds ...gen.Condition) IStudyCommentReplyDo
	Select(conds ...field.Expr) IStudyCommentReplyDo
	Where(conds ...gen.Condition) IStudyCommentReplyDo
	Order(conds ...field.Expr) IStudyCommentReplyDo
	Distinct(cols ...field.Expr) IStudyCommentReplyDo
	Omit(cols ...field.Expr) IStudyCommentReplyDo
	Join(table schema.Tabler, on ...field.Expr) IStudyCommentReplyDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IStudyCommentReplyDo
	RightJoin(table schema.Tabler, on ...field.Expr) IStudyCommentReplyDo
	Group(cols ...field.Expr) IStudyCommentReplyDo
	Having(conds ...gen.Condition) IStudyCommentReplyDo
	Limit(limit int) IStudyCommentReplyDo
	Offset(offset int) IStudyCommentReplyDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IStudyCommentReplyDo
	Unscoped() IStudyCommentReplyDo
	Create(values ...*model.StudyCommentReply) error
	CreateInBatches(values []*model.StudyCommentReply, batchSize int) error
	Save(values ...*model.StudyCommentReply) error
	First() (*model.StudyCommentReply, error)
	Take() (*model.StudyCommentReply, error)
	Last() (*model.StudyCommentReply, error)
	Find() ([]*model.StudyCommentReply, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StudyCommentReply, err error)
	FindInBatches(result *[]*model.StudyCommentReply, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.StudyCommentReply) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IStudyCommentReplyDo
	Assign(attrs ...field.AssignExpr) IStudyCommentReplyDo
	Joins(fields ...field.RelationField) IStudyCommentReplyDo
	Preload(fields ...field.RelationField) IStudyCommentReplyDo
	FirstOrInit() (*model.StudyCommentReply, error)
	FirstOrCreate() (*model.StudyCommentReply, error)
	FindByPage(offset int, limit int) (result []*model.StudyCommentReply, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IStudyCommentReplyDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s studyCommentReplyDo) Debug() IStudyCommentReplyDo {
	return s.withDO(s.DO.Debug())
}

func (s studyCommentReplyDo) WithContext(ctx context.Context) IStudyCommentReplyDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s studyCommentReplyDo) ReadDB() IStudyCommentReplyDo {
	return s.Clauses(dbresolver.Read)
}

func (s studyCommentReplyDo) WriteDB() IStudyCommentReplyDo {
	return s.Clauses(dbresolver.Write)
}

func (s studyCommentReplyDo) Session(config *gorm.Session) IStudyCommentReplyDo {
	return s.withDO(s.DO.Session(config))
}

func (s studyCommentReplyDo) Clauses(conds ...clause.Expression) IStudyCommentReplyDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s studyCommentReplyDo) Returning(value interface{}, columns ...string) IStudyCommentReplyDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s studyCommentReplyDo) Not(conds ...gen.Condition) IStudyCommentReplyDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s studyCommentReplyDo) Or(conds ...gen.Condition) IStudyCommentReplyDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s studyCommentReplyDo) Select(conds ...field.Expr) IStudyCommentReplyDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s studyCommentReplyDo) Where(conds ...gen.Condition) IStudyCommentReplyDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s studyCommentReplyDo) Order(conds ...field.Expr) IStudyCommentReplyDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s studyCommentReplyDo) Distinct(cols ...field.Expr) IStudyCommentReplyDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s studyCommentReplyDo) Omit(cols ...field.Expr) IStudyCommentReplyDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s studyCommentReplyDo) Join(table schema.Tabler, on ...field.Expr) IStudyCommentReplyDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s studyCommentReplyDo) LeftJoin(table schema.Tabler, on ...field.Expr) IStudyCommentReplyDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s studyCommentReplyDo) RightJoin(table schema.Tabler, on ...field.Expr) IStudyCommentReplyDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s studyCommentReplyDo) Group(cols ...field.Expr) IStudyCommentReplyDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s studyCommentReplyDo) Having(conds ...gen.Condition) IStudyCommentReplyDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s studyCommentReplyDo) Limit(limit int) IStudyCommentReplyDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s studyCommentReplyDo) Offset(offset int) IStudyCommentReplyDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s studyCommentReplyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IStudyCommentReplyDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s studyCommentReplyDo) Unscoped() IStudyCommentReplyDo {
	return s.withDO(s.DO.Unscoped())
}

func (s studyCommentReplyDo) Create(values ...*model.StudyCommentReply) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s studyCommentReplyDo) CreateInBatches(values []*model.StudyCommentReply, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s studyCommentReplyDo) Save(values ...*model.StudyCommentReply) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s studyCommentReplyDo) First() (*model.StudyCommentReply, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.StudyCommentReply), nil
	}
}

func (s studyCommentReplyDo) Take() (*model.StudyCommentReply, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.StudyCommentReply), nil
	}
}

func (s studyCommentReplyDo) Last() (*model.StudyCommentReply, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.StudyCommentReply), nil
	}
}

func (s studyCommentReplyDo) Find() ([]*model.StudyCommentReply, error) {
	result, err := s.DO.Find()
	return result.([]*model.StudyCommentReply), err
}

func (s studyCommentReplyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StudyCommentReply, err error) {
	buf := make([]*model.StudyCommentReply, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s studyCommentReplyDo) FindInBatches(result *[]*model.StudyCommentReply, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s studyCommentReplyDo) Attrs(attrs ...field.AssignExpr) IStudyCommentReplyDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s studyCommentReplyDo) Assign(attrs ...field.AssignExpr) IStudyCommentReplyDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s studyCommentReplyDo) Joins(fields ...field.RelationField) IStudyCommentReplyDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s studyCommentReplyDo) Preload(fields ...field.RelationField) IStudyCommentReplyDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s studyCommentReplyDo) FirstOrInit() (*model.StudyCommentReply, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.StudyCommentReply), nil
	}
}

func (s studyCommentReplyDo) FirstOrCreate() (*model.StudyCommentReply, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.StudyCommentReply), nil
	}
}

func (s studyCommentReplyDo) FindByPage(offset int, limit int) (result []*model.StudyCommentReply, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s studyCommentReplyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s studyCommentReplyDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s studyCommentReplyDo) Delete(models ...*model.StudyCommentReply) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *studyCommentReplyDo) withDO(do gen.Dao) *studyCommentReplyDo {
	s.DO = *do.(*gen.DO)
	return s
}
