// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"comment-service/dal/model"
)

func newStudyComment(db *gorm.DB, opts ...gen.DOOption) studyComment {
	_studyComment := studyComment{}

	_studyComment.studyCommentDo.UseDB(db, opts...)
	_studyComment.studyCommentDo.UseModel(&model.StudyComment{})

	tableName := _studyComment.studyCommentDo.TableName()
	_studyComment.ALL = field.NewAsterisk(tableName)
	_studyComment.ID = field.NewInt64(tableName, "id")
	_studyComment.CommentID = field.NewInt64(tableName, "comment_id")
	_studyComment.PostID = field.NewInt64(tableName, "post_id")
	_studyComment.StudentID = field.NewInt64(tableName, "student_id")
	_studyComment.Content = field.NewString(tableName, "content")
	_studyComment.VisibleStatus = field.NewInt32(tableName, "visible_status")
	_studyComment.AuditStatus = field.NewInt32(tableName, "audit_status")
	_studyComment.ManualReviewReason = field.NewString(tableName, "manual_review_reason")
	_studyComment.ManualOperatorID = field.NewInt64(tableName, "manual_operator_id")
	_studyComment.ReplyID = field.NewInt64(tableName, "reply_id")
	_studyComment.ReplyTutorID = field.NewInt64(tableName, "reply_tutor_id")
	_studyComment.ReplyContent = field.NewString(tableName, "reply_content")
	_studyComment.ReplyStatus = field.NewInt32(tableName, "reply_status")
	_studyComment.RepliedAt = field.NewTime(tableName, "replied_at")
	_studyComment.DeletedAt = field.NewField(tableName, "deleted_at")
	_studyComment.CreatedAt = field.NewTime(tableName, "created_at")
	_studyComment.UpdatedAt = field.NewTime(tableName, "updated_at")

	_studyComment.fillFieldMap()

	return _studyComment
}

// studyComment 学生学习打卡评论表
type studyComment struct {
	studyCommentDo studyCommentDo

	ALL                field.Asterisk
	ID                 field.Int64
	CommentID          field.Int64  // 学生评论ID
	PostID             field.Int64  // 知识帖ID
	StudentID          field.Int64  // 评论学生ID
	Content            field.String // 评论内容
	VisibleStatus      field.Int32  // 1可见 2不可见
	AuditStatus        field.Int32  // 0待审核 1审核通过 2审核驳回
	ManualReviewReason field.String // 人工驳回原因
	ManualOperatorID   field.Int64  // 运营ID
	ReplyID            field.Int64  // 助教回复ID
	ReplyTutorID       field.Int64  // 回复助教ID
	ReplyContent       field.String // 助教一次性指导回复
	ReplyStatus        field.Int32  // 0未回复 1已回复 2已撤回
	RepliedAt          field.Time   // 回复时间
	DeletedAt          field.Field  // 删除时间
	CreatedAt          field.Time
	UpdatedAt          field.Time

	fieldMap map[string]field.Expr
}

func (s studyComment) Table(newTableName string) *studyComment {
	s.studyCommentDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s studyComment) As(alias string) *studyComment {
	s.studyCommentDo.DO = *(s.studyCommentDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *studyComment) updateTableName(table string) *studyComment {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.CommentID = field.NewInt64(table, "comment_id")
	s.PostID = field.NewInt64(table, "post_id")
	s.StudentID = field.NewInt64(table, "student_id")
	s.Content = field.NewString(table, "content")
	s.VisibleStatus = field.NewInt32(table, "visible_status")
	s.AuditStatus = field.NewInt32(table, "audit_status")
	s.ManualReviewReason = field.NewString(table, "manual_review_reason")
	s.ManualOperatorID = field.NewInt64(table, "manual_operator_id")
	s.ReplyID = field.NewInt64(table, "reply_id")
	s.ReplyTutorID = field.NewInt64(table, "reply_tutor_id")
	s.ReplyContent = field.NewString(table, "reply_content")
	s.ReplyStatus = field.NewInt32(table, "reply_status")
	s.RepliedAt = field.NewTime(table, "replied_at")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *studyComment) WithContext(ctx context.Context) IStudyCommentDo {
	return s.studyCommentDo.WithContext(ctx)
}

func (s studyComment) TableName() string { return s.studyCommentDo.TableName() }

func (s studyComment) Alias() string { return s.studyCommentDo.Alias() }

func (s studyComment) Columns(cols ...field.Expr) gen.Columns {
	return s.studyCommentDo.Columns(cols...)
}

func (s *studyComment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *studyComment) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 17)
	s.fieldMap["id"] = s.ID
	s.fieldMap["comment_id"] = s.CommentID
	s.fieldMap["post_id"] = s.PostID
	s.fieldMap["student_id"] = s.StudentID
	s.fieldMap["content"] = s.Content
	s.fieldMap["visible_status"] = s.VisibleStatus
	s.fieldMap["audit_status"] = s.AuditStatus
	s.fieldMap["manual_review_reason"] = s.ManualReviewReason
	s.fieldMap["manual_operator_id"] = s.ManualOperatorID
	s.fieldMap["reply_id"] = s.ReplyID
	s.fieldMap["reply_tutor_id"] = s.ReplyTutorID
	s.fieldMap["reply_content"] = s.ReplyContent
	s.fieldMap["reply_status"] = s.ReplyStatus
	s.fieldMap["replied_at"] = s.RepliedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s studyComment) clone(db *gorm.DB) studyComment {
	s.studyCommentDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s studyComment) replaceDB(db *gorm.DB) studyComment {
	s.studyCommentDo.ReplaceDB(db)
	return s
}

type studyCommentDo struct{ gen.DO }

type IStudyCommentDo interface {
	gen.SubQuery
	Debug() IStudyCommentDo
	WithContext(ctx context.Context) IStudyCommentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IStudyCommentDo
	WriteDB() IStudyCommentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IStudyCommentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IStudyCommentDo
	Not(conds ...gen.Condition) IStudyCommentDo
	Or(conds ...gen.Condition) IStudyCommentDo
	Select(conds ...field.Expr) IStudyCommentDo
	Where(conds ...gen.Condition) IStudyCommentDo
	Order(conds ...field.Expr) IStudyCommentDo
	Distinct(cols ...field.Expr) IStudyCommentDo
	Omit(cols ...field.Expr) IStudyCommentDo
	Join(table schema.Tabler, on ...field.Expr) IStudyCommentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IStudyCommentDo
	RightJoin(table schema.Tabler, on ...field.Expr) IStudyCommentDo
	Group(cols ...field.Expr) IStudyCommentDo
	Having(conds ...gen.Condition) IStudyCommentDo
	Limit(limit int) IStudyCommentDo
	Offset(offset int) IStudyCommentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IStudyCommentDo
	Unscoped() IStudyCommentDo
	Create(values ...*model.StudyComment) error
	CreateInBatches(values []*model.StudyComment, batchSize int) error
	Save(values ...*model.StudyComment) error
	First() (*model.StudyComment, error)
	Take() (*model.StudyComment, error)
	Last() (*model.StudyComment, error)
	Find() ([]*model.StudyComment, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StudyComment, err error)
	FindInBatches(result *[]*model.StudyComment, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.StudyComment) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IStudyCommentDo
	Assign(attrs ...field.AssignExpr) IStudyCommentDo
	Joins(fields ...field.RelationField) IStudyCommentDo
	Preload(fields ...field.RelationField) IStudyCommentDo
	FirstOrInit() (*model.StudyComment, error)
	FirstOrCreate() (*model.StudyComment, error)
	FindByPage(offset int, limit int) (result []*model.StudyComment, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IStudyCommentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s studyCommentDo) Debug() IStudyCommentDo {
	return s.withDO(s.DO.Debug())
}

func (s studyCommentDo) WithContext(ctx context.Context) IStudyCommentDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s studyCommentDo) ReadDB() IStudyCommentDo {
	return s.Clauses(dbresolver.Read)
}

func (s studyCommentDo) WriteDB() IStudyCommentDo {
	return s.Clauses(dbresolver.Write)
}

func (s studyCommentDo) Session(config *gorm.Session) IStudyCommentDo {
	return s.withDO(s.DO.Session(config))
}

func (s studyCommentDo) Clauses(conds ...clause.Expression) IStudyCommentDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s studyCommentDo) Returning(value interface{}, columns ...string) IStudyCommentDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s studyCommentDo) Not(conds ...gen.Condition) IStudyCommentDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s studyCommentDo) Or(conds ...gen.Condition) IStudyCommentDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s studyCommentDo) Select(conds ...field.Expr) IStudyCommentDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s studyCommentDo) Where(conds ...gen.Condition) IStudyCommentDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s studyCommentDo) Order(conds ...field.Expr) IStudyCommentDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s studyCommentDo) Distinct(cols ...field.Expr) IStudyCommentDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s studyCommentDo) Omit(cols ...field.Expr) IStudyCommentDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s studyCommentDo) Join(table schema.Tabler, on ...field.Expr) IStudyCommentDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s studyCommentDo) LeftJoin(table schema.Tabler, on ...field.Expr) IStudyCommentDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s studyCommentDo) RightJoin(table schema.Tabler, on ...field.Expr) IStudyCommentDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s studyCommentDo) Group(cols ...field.Expr) IStudyCommentDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s studyCommentDo) Having(conds ...gen.Condition) IStudyCommentDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s studyCommentDo) Limit(limit int) IStudyCommentDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s studyCommentDo) Offset(offset int) IStudyCommentDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s studyCommentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IStudyCommentDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s studyCommentDo) Unscoped() IStudyCommentDo {
	return s.withDO(s.DO.Unscoped())
}

func (s studyCommentDo) Create(values ...*model.StudyComment) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s studyCommentDo) CreateInBatches(values []*model.StudyComment, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s studyCommentDo) Save(values ...*model.StudyComment) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s studyCommentDo) First() (*model.StudyComment, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.StudyComment), nil
	}
}

func (s studyCommentDo) Take() (*model.StudyComment, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.StudyComment), nil
	}
}

func (s studyCommentDo) Last() (*model.StudyComment, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.StudyComment), nil
	}
}

func (s studyCommentDo) Find() ([]*model.StudyComment, error) {
	result, err := s.DO.Find()
	return result.([]*model.StudyComment), err
}

func (s studyCommentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StudyComment, err error) {
	buf := make([]*model.StudyComment, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s studyCommentDo) FindInBatches(result *[]*model.StudyComment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s studyCommentDo) Attrs(attrs ...field.AssignExpr) IStudyCommentDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s studyCommentDo) Assign(attrs ...field.AssignExpr) IStudyCommentDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s studyCommentDo) Joins(fields ...field.RelationField) IStudyCommentDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s studyCommentDo) Preload(fields ...field.RelationField) IStudyCommentDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s studyCommentDo) FirstOrInit() (*model.StudyComment, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.StudyComment), nil
	}
}

func (s studyCommentDo) FirstOrCreate() (*model.StudyComment, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.StudyComment), nil
	}
}

func (s studyCommentDo) FindByPage(offset int, limit int) (result []*model.StudyComment, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s studyCommentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s studyCommentDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s studyCommentDo) Delete(models ...*model.StudyComment) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *studyCommentDo) withDO(do gen.Dao) *studyCommentDo {
	s.DO = *do.(*gen.DO)
	return s
}
